//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class extrawyken2
    {
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<long> wykno { get; set; }
        public string tydsduur { get; set; }
        public string depot { get; set; }
        public int id { get; set; }
        public Nullable<bool> discontinued { get; set; }
        public string errorwijken { get; set; }
    }
}
