//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace WebApplication4
{
    
    
    public partial class persgroepoverzicht
    {
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> wykno { get; set; }
        public Nullable<int> aantalbndestem { get; set; }
        public Nullable<decimal> stuksprijsbndestem { get; set; }
        public Nullable<int> aantaltelegraaf { get; set; }
        public Nullable<decimal> stuksprijstelegraaf { get; set; }
        public Nullable<int> aantalad { get; set; }
        public Nullable<decimal> stuksprijsad { get; set; }
        public Nullable<int> aantalvolkskrant { get; set; }
        public Nullable<decimal> stuksprijsvolkskrant { get; set; }
        public Nullable<int> aantaltrouw { get; set; }
        public Nullable<decimal> stuksprijstrouw { get; set; }
        public Nullable<int> aantalnederlandsdagblad { get; set; }
        public Nullable<decimal> stuksprijsnederlandsdagblad { get; set; }
        public Nullable<int> aantalnrcnext { get; set; }
        public Nullable<decimal> stuksprijsnrcnext { get; set; }
        public Nullable<int> aantalfinancieeldagblad { get; set; }
        public Nullable<decimal> stuksprijsfinancieeldagblad { get; set; }
        public Nullable<int> aantalkidsweek { get; set; }
        public Nullable<decimal> stuksprijskidsweek { get; set; }
        public Nullable<int> aantalsevendays { get; set; }
        public Nullable<decimal> stuksprijssevendays { get; set; }
        public Nullable<int> totaalbndestem { get; set; }
        public Nullable<int> totaaltelegraaf { get; set; }
        public Nullable<int> totaalad { get; set; }
        public Nullable<int> totaalvolkskrant { get; set; }
        public Nullable<int> totaaltrouw { get; set; }
        public Nullable<int> totaalnederlandsdagblad { get; set; }
        public Nullable<int> totaalnrcnext { get; set; }
        public Nullable<int> totaalfinancieeldagblad { get; set; }
        public Nullable<int> totaalkidsweek { get; set; }
        public Nullable<int> totaalsevendays { get; set; }
        public Nullable<decimal> totaalvergoedingen { get; set; }
        public Nullable<decimal> totaaladjectieven { get; set; }
        public string bijzonderhedenperiode { get; set; }
        public int id { get; set; }
        public Nullable<bool> discontinued { get; set; }
    }
}
