//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;




namespace WebApplication4
{
    
    
    public partial class persgroep
    {
        public Nullable<long> wykno { get; set; }
        public string straatnaam { get; set; }
        public string bndestem { get; set; }
        public string telegraaf { get; set; }
        public string algemeendagblad { get; set; }
        public string volkskrant { get; set; }
        public string trouw { get; set; }
        public string nederlandsdagblad { get; set; }
        public string nrcnext { get; set; }
        public string financieeldagblad { get; set; }
        public string kidsweek { get; set; }
        public string sevendays { get; set; }
        public string bijzonderheden { get; set; }
        public int id { get; set; }
        public Nullable<bool> discontinued { get; set; }
    }
}
